version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "63793:6379"
    networks:
      default:
        ipv4_address: 172.15.0.4
  nginx:
    build:
      context: ./docker/nginx
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm
    networks:
      default:
        ipv4_address: 172.15.0.2
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        NODE_VERSION: 10.24.1
    working_dir: /app
    volumes:
      - ./app:/app
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      TZ: "Europe/Moscow"
    networks:
      default:
        ipv4_address: 172.15.0.3
        aliases:
          - app
  db:
    image: postgres:14.8
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: lp2
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lp2
    networks:
      default:
        ipv4_address: 172.15.0.5

networks:
  default:
      name: lp2_net
      external: true

